select 
O.ORDERID,
O.ORDERDATE,
O.SHIPDATE,
O.SHIPMODE,
C.CUSTOMERNAME,
C.CUSTOMERID,
C.SEGMENT,
C.COUNTRY,
P.CATEGORY,
p.PRODUCTID,
P.PRODUCTNAME,
P.SUBCATEGORY,
O.ORDERSELLINGPRICE-O.ORDERCOSTPRICE as ORDERPROFIT,
O.ORDERCOSTPRICE,
O.ORDERSELLINGPRICE
from {{ ref('RAW_ORDERS') }} AS O
LEFT JOIN {{ ref('RAW_CUSTOMER') }} AS C
ON O.CUSTOMERID = C.CUSTOMERID
LEFT JOIN {{ ref('RAW_PRODUCT') }} AS P
ON O.PRODUCTID = P.PRODUCTID

